### ISSUE TITLE
update marketplace dependency in package.json

### ISSUE THREAD

**Issue by sravyadalavai-vl** [ScaleLeap/amazon-advertising-api-sdk#753]
current package.json file having the "@scaleleap/amazon-marketplaces": "10.3.0" this version. but it should update to new version.
![image](https://user-images.githubusercontent.com/69245200/116524705-50bdc500-a8f5-11eb-9e2a-913a1b0d8c4c.png)

**Comment by sravyadalavai-vl** [comment]
Because of that still i am getting the error.
DecodeError: Invalid value "Europe/Amsterdam" supplied to : Array<({ profileId: number, countryCode: enum, currencyCode: enum, timezone: enum, accountInfo: ({ marketplaceStringId: string, id: string, type: ("seller" | "vendor" | "agency") } & Partial<{ name: string, subType: ("KDP_AUTHOR" | "AMAZON_ATTRIBUTION") }>) } & Partial<{ dailyBudget: number }>)>/5: ({ profileId: number, countryCode: enum, currencyCode: enum, timezone: enum, accountInfo: ({ marketplaceStringId: string, id: string, type: ("seller" | "vendor" | "agency") } & Partial<{ name: string, subType: ("KDP_AUTHOR" | "AMAZON_ATTRIBUTION") }>) } & Partial<{ dailyBudget: number }>)/0: { profileId: number, countryCode: enum, currencyCode: enum, timezone: enum, accountInfo: ({ marketplaceStringId: string, id: string, type: ("seller" | "vendor" | "agency") } & Partial<{ name: string, subType: ("KDP_AUTHOR" | "AMAZON_ATTRIBUTION") }>) }/timezone: enum
at new DecodeError (D:\Projects\Luzern\gitCode\amazonadvertisingmanagement\amplify\backend\function\GetAmazonSnapshotData\src\node_modules\io-ts-promise\lib\index.js:55:28)
at D:\Projects\Luzern\gitCode\amazonadvertisingmanagement\amplify\backend\function\GetAmazonSnapshotData\src\node_modules\io-ts-promise\lib\index.js:37:76
at D:\Projects\Luzern\gitCode\amazonadvertisingmanagement\amplify\backend\function\GetAmazonSnapshotData\src\node_modules\fp-ts\lib\Either.js:245:57
at Object.decode (D:\Projects\Luzern\gitCode\amazonadvertisingmanagement\amplify\backend\function\GetAmazonSnapshotData\src\node_modules\io-ts-promise\lib\index.js:37:171)
at D:\Projects\Luzern\gitCode\amazonadvertisingmanagement\amplify\backend\function\GetAmazonSnapshotData\src\node_modules@luzernsolutions\serverless-sdk-backend-amazonapi\node_modules@scaleleap\amazon-advertising-api-sdk\lib\decorators.js:34:97
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async Object.exports.GetOperationProvider (D:\Projects\Luzern\gitCode\amazonadvertisingmanagement\amplify\backend\function\GetAmazonSnapshotData\src\node_modules@luzernsolutions\serverless-sdk-backend-amazonapi\index.js:37:21)
at async snapShotDataInsertion (D:\Projects\Luzern\gitCode\amazonadvertisingmanagement\amplify\backend\function\GetAmazonSnapshotData\src\index.js:26:35)
at async exports.handler (D:\Projects\Luzern\gitCode\amazonadvertisingmanagement\amplify\backend\function\GetAmazonSnapshotData\src\index.js:10:24)
at async c:\Users\sravya.dalavai\AppData\Roaming\npm\node_modules@aws-amplify\cli\node_modules\amplify-nodejs-function-runtime-provider\lib\utils\execute.js:91:32 {name: 'DecodeError', errors: Array(1), stack: 'DecodeError: Invalid value "Europe/Amsterdam"…n-runtime-provider\lib\utils\execute.js:91:32', message: 'Invalid value "Europe/Amsterdam" supplied to…| "AMAZON_ATTRIBUTION") }>) }/timezone: enum'}
